name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Trivy Filesystem Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
